version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:18.04-browsers

    steps:
      - checkout

      - run:
          name: test
          command: apt-get install libcunit1 libcunit1-doc libcunit1-dev
            make check

      - run:
          name: build
          command: make