version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: test
          command: make check

      - run:
          name: build
          command: make